# Handle git submodules yourself
git:
    submodules: false
# See: https://gist.github.com/iedemam/9830045
before_install:
    - git submodule update --init --recursive
language: php
php:
  - 7.0
script: phpunit AlertinatorTest.php
