name: PHPUnit

on: push

jobs:
  run:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: ['7.3', '7.4', '8.0', '8.1', '8.2']

    steps:
       - uses: actions/checkout@v3
       - run: sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
       - run: git submodule update --init --recursive

       - uses: shivammathur/setup-php@v2
         with:
           php-version: ${{ matrix.php-versions }}
           tools: phpunit:9

       - name: Run unit tests
         run: phpunit AlertinatorTest.php
